name: Environment Deployment Active Check
description: Check whether a GitHub environment already has an active deployment for a given ref/commit.
author: remedyproduct
branding:
  icon: check-circle
  color: blue

inputs:
  token:
    description: GitHub token with access to deployments API (defaults to github.token)
    required: false
  environment:
    description: Target GitHub environment name (e.g. qa, stage, production)
    required: true
  ref:
    description: Git ref name to compare against (branch or full ref). Defaults to main.
    required: false
    default: main

outputs:
  should_deploy:
    description: "'true' if there is no active deployment for this ref in the target environment; 'false' otherwise."
    value: ${{ steps.check.outputs.should_deploy }}
  current_sha:
    description: SHA of the target ref used for comparison.
    value: ${{ steps.check.outputs.current_sha }}
  active_sha:
    description: SHA of the currently active deployment in the target environment (if any).
    value: ${{ steps.check.outputs.active_sha }}

runs:
  using: composite
  steps:
    - name: Determine active deployment for environment
      id: check
      uses: actions/github-script@v7
      env:
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        INPUT_REF: ${{ inputs.ref }}
      with:
        github-token: ${{ inputs.token || github.token }}
        script: |
          const envName = process.env.INPUT_ENVIRONMENT;
          const refInput = process.env.INPUT_REF || 'main';

          const owner = context.repo.owner;
          const repo = context.repo.repo;

          // Normalize ref: accept either plain branch name or refs/heads/branch
          const refName = refInput.replace(/^refs\/(heads|tags)\//, '');

          // Resolve target SHA for given ref (branch)
          const ref = await github.rest.git.getRef({
            owner,
            repo,
            ref: `heads/${refName}`,
          });
          const targetSha = ref.data.object.sha;

          // List deployments for the target environment (newest first)
          const deployments = await github.paginate(
            github.rest.repos.listDeployments,
            { owner, repo, environment: envName, per_page: 20 }
          );

          let activeSha = null;
          for (const dep of deployments) {
            const { data: statuses } = await github.rest.repos.listDeploymentStatuses({
              owner,
              repo,
              deployment_id: dep.id,
              per_page: 10,
            });

            const latestStatus = statuses[0];
            if (latestStatus && latestStatus.state === 'active') {
              activeSha = dep.sha;
              break;
            }
          }

          core.info(`environment: ${envName}`);
          core.info(`target ref: ${refName}`);
          core.info(`target sha: ${targetSha}`);
          core.info(`active sha: ${activeSha}`);

          const shouldDeploy = !activeSha || activeSha !== targetSha;

          core.setOutput('should_deploy', shouldDeploy ? 'true' : 'false');
          core.setOutput('current_sha', targetSha);
          core.setOutput('active_sha', activeSha || '');
